name: Backend CD
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  cd:
    runs-on: ubuntu-latest
  #    needs: ci
  
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest
